name: hl_image_picker_android
description: Android implementation of the hl_image_picker plugin.
repository: https://github.com/howljs/hl_image_picker/tree/main/hl_image_picker_android
issue_tracker: https://github.com/howljs/hl_image_picker/issues

version: 1.2.4

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  hl_image_picker_platform_interface: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.howl.hl_image_picker
        pluginClass: HLImagePickerPlugin
        dartPluginClass: HLImagePickerAndroid
